# Caso de Estudio - Codificación de valores categóricos en matrices de activación

In [5]:
import numpy as np

x1 = ["POSITIVO", "POSITIVO", "NEGATIVO", "NEUTRO", "NEGATIVO"]

np.unique(x1)

array(['NEGATIVO', 'NEUTRO', 'POSITIVO'], dtype='<U8')

In [6]:
import pandas as pd

pd.DataFrame({ "x1": x1 }).groupby("x1")["x1"].agg("count")

x1
NEGATIVO    2
NEUTRO      1
POSITIVO    2
Name: x1, dtype: int64

In [8]:
y = [0, 0, 1, 1, 0]

pd.DataFrame({"x1": x1, "y": y})

x1  y
0  POSITIVO  0
1  POSITIVO  0
2  NEGATIVO  1
3    NEUTRO  1
4  NEGATIVO  0

In [10]:
x2 = ["COMPRA", "NO-COMPRA", "COMPRA", "NO-COMPRA", "NO-COMPRA"]

pd.DataFrame({"x1": x1, "x2": x2, "y": y})

x1         x2  y
0  POSITIVO     COMPRA  0
1  POSITIVO  NO-COMPRA  0
2  NEGATIVO     COMPRA  1
3    NEUTRO  NO-COMPRA  1
4  NEGATIVO  NO-COMPRA  0

In [11]:
X = pd.DataFrame({"x1": x1, "x2": x2}).values

X

array([['POSITIVO', 'COMPRA'],
       ['POSITIVO', 'NO-COMPRA'],
       ['NEGATIVO', 'COMPRA'],
       ['NEUTRO', 'NO-COMPRA'],
       ['NEGATIVO', 'NO-COMPRA']], dtype=object)

In [19]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()

enc.fit(X)

enc.categories_

[array(['NEGATIVO', 'NEUTRO', 'POSITIVO'], dtype=object),
 array(['COMPRA', 'NO-COMPRA'], dtype=object)]

In [21]:
enc.transform(X).toarray()

array([[0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

Hasta este punto nosotros disponemos de un eje `x1` categórico y un eje `x2` también categórico, el cual podemos codificar en 5 columnas, 3 columnas para representar las categorías de `x1` y 2 columnas para las posibles categorías de `x2`.

Pero, si hubiera una tercera columna `x3` no categórica, ¿Qué pasaría en el flujo? 

In [22]:
x3 = [100, 120, 80, 67, 90]

import pandas as pd

X2 = pd.DataFrame({ "x1": x1, "x2": x2, "x3": x3 }).values

X2

array([['POSITIVO', 'COMPRA', 100],
       ['POSITIVO', 'NO-COMPRA', 120],
       ['NEGATIVO', 'COMPRA', 80],
       ['NEUTRO', 'NO-COMPRA', 67],
       ['NEGATIVO', 'NO-COMPRA', 90]], dtype=object)

In [23]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()

enc.fit(X2)

enc.categories_

[array(['NEGATIVO', 'NEUTRO', 'POSITIVO'], dtype=object),
 array(['COMPRA', 'NO-COMPRA'], dtype=object),
 array([67, 80, 90, 100, 120], dtype=object)]

In [25]:
Xe = enc.fit_transform(X[:, 0:2]).toarray()

Xe

array([[0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [28]:
Xe = enc.fit_transform(X2).toarray()

Xe

array([[0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0., 0.]])